
# Admin server & Config server require to configure ( Not AutoConfigure by defult by SpringBoot and SpringCloud)
spring.boot.admin.client.url=http://localhost:1111/


# Not require to configure Eureka and Zipkin server, they automatically configure  (AutoConfigure by defult by SpringBoot and SpringCloud)
# eureka.client.service-url.default-zone=http://localhost:9000/eureka/
# management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

#server.port=8081

management.endpoints.web.exposure.include=*, refresh
